version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: platform-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: platform_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_platform:/var/lib/postgresql/data

  # api:
  #   build: .
  #   container_name: platform-api
  #   restart: always
  #   ports:
  #     - '5000:5000'
  #   environment:
  #     NODE_ENV: 'development'
  #     PORT: 5000
  #     DATABASE_URL: 'postgresql://postgres:postgres123@postgres:5432/platform_db'
  #     ACCESS_TOKEN_SECRET: 'access123'
  #     REFRESH_TOKEN_SECRET: 'refresh123'
  #   depends_on:
  #     - postgres

volumes:
  postgres_data_platform:
